USER_INPUT_ID = "ctl00_ContentPlaceHolder1_txtUsuario"
PASSWORD_INPUT_ID = "ctl00_ContentPlaceHolder1_txtContraseña"
LOGIN_BUTTON_ID = "btnIngresarUsuarioContraseña"
TOKEN_INPUT_ID = "ctl00_ContentPlaceHolder1_txtTokenEntrust"
TOKEN_LOGIN_BUTTON_ID = "ctl00_ContentPlaceHolder1_BtnLoginTokenEntrust"
SELECTOR_MIGRATION_BUTTON = "a[href='/POL_MENU/Menu/GoToApp?IdItem=471']"
SELECTOR_FLYERS_NIT = "a[href='/Recaudo.PS/Dispatcher/EntranceVolantesNIT']"
SELECT_DISTRIBUTOR = "Distr"
SELECT_TYPE = "idTipoVolante"
SELECT_INITIALDATE = "idinitialDate"
SELECT_FINALDATE = "idfinalDate"
BUTTON_FLYERS = "btnConsultar"
BUTTON_SEE_FLYERS = "#contentOptions a[href*='ConsultaVolantesNIT']"
BUTTON_SEND_PRINT_FLYERS = "cmdImprimir"
SELECT_PRINTER = "(//select[@class='md-select'])[0]"
BUTTON_NEW_SEARCH = "a[href='/Recaudo.PS/VolantesNIT/Index']"
SELECT_ALL_VOLANTES = BUTTON_SEE_FLYERS
BOTON_CANCELAR_VOLANTE = "cmdCancelar"
CANCEL_BUTTON = "cancel-button"
BUTTON_MENU="a[href='/Recaudo.PS/Dispatcher/MainMenu']"
BUTTON_SPREADSHEETS ="a[href='/POL_MENU/Menu/GoToApp?IdItem=504']"
SELECT_SPREADSHEETS="//a[contains(@class,'menuLateralHomePoliedro')][.//span[contains(normalize-space(.), 'Planillado')]]"
GO_TO_SPREADHEETS="a[href='/POL_MENU/Menu/GoToApp?IdItem=251']"
GENERATE_SPREADSHEETS="a[href='/GestionPlanillas/Generar/FiltrosPlanilla.aspx']"
SELECT_USER_NAME ="cpContenido_WucFiltrosPlanilla_DdlCodActivacion"
SELECT_OFFICE ="cpContenido_WucFiltrosPlanilla_DdlPuntoDeVenta"
SELECT_GENERATION_TYPE = "cpContenido_WucFiltrosPlanilla_DdlTipoGeneracion"
SELECT_SPREADSHEET_TYPE ="cpContenido_WucFiltrosPlanilla_DdlTipoPlanillado"
SELECT_SPREADSHEET_IN_SPREADSHEET = "cpContenido_WucFiltrosPlanilla_DdlPlanilla"
SELECT_PRODUCT = "cpContenido_WucFiltrosPlanilla_DdlProducto"
SELECT_TYPE_OF_SALE= "cpContenido_WucFiltrosPlanilla_DdlTipoVenta"
START_DATE= "cpContenido_WucFiltrosPlanilla_ImbFechaInicial"
BUTTON_CONFIRMAR_GENERACION = "cpContenido_WucFiltrosPlanilla_BtnAceptar"
BUTTON_YES_SPREADSHEET="cpContenido_WucFiltrosPlanilla_btnYes"
BUTTON_NOT_SPREADSHEET="cpContenido_WucFiltrosPlanilla_WucMensaje_btnAcepta"
TABLE_PLANILLA = "cpContenido_WucFiltrosPlanilla_WucCargaInicialPlanilla_GrvRegistros"
BUTTON_SIMULAR = "cpContenido_WucFiltrosPlanilla_BtnSimular"
BUTTON_GENERAR_PLANILLA = "cpContenido_WucFiltrosPlanilla_BtnGenerarPlanilla"
BUTTON_CONTINUAR = "cpContenido_WucFiltrosPlanilla_BtnContinuar"

BUTTON_CONSULTAR_PLANILLA = "a[href='ConsultarPlanilla.aspx']"
SELECT_ASESOR="cpContenido_WucConsultarPlanilla_DdlCodActivacion"
SELECT_PUNTO_VENTA="cpContenido_WucConsultarPlanilla_DdlPuntoDeVenta"
SELECT_TIPO_VENTA="cpContenido_WucConsultarPlanilla_DdlTipoConsulta"
SELECT_TIPO_PLANILLADO="cpContenido_WucConsultarPlanilla_DdlTipoPlanillado"
SELECT_PLANILLADO="cpContenido_WucConsultarPlanilla_DdlPlanilla"
SELECT_PRODUCTO="cpContenido_WucConsultarPlanilla_DdlProducto"
INPUT_PLANILLA="cpContenido_WucConsultarPlanilla_TxtNumPlanilla"
BOTON_SEGUIR="cpContenido_WucConsultarPlanilla_BtnAceptar"
BOTON_ACEPTAR_CONSULTA="cpContenido_WucConsultarPlanilla_btnYes"
VALOR_TOTAL_TABLA_PLANILLA = "cpContenido_WucFiltrosPlanilla_WucCargaSimulada_WucListaPagos_GrvTipoPagos_LblValTotal"
TARJETA_CREDITO_TABLA_PLANILLA = "cpContenido_WucFiltrosPlanilla_WucCargaSimulada_WucListaPagos_GrvTipoPagos_Label2_1"
